import { Button } from "std-widgets.slint";

component Indicator inherits HorizontalLayout {
    in-out property <bool> isOn: false;
    Rectangle {
        border-radius: 20px;
        border-color: black;
        border-width: 4px;
        background: isOn ? green : red;
        width: 100px;

        VerticalLayout {
            alignment: center;
            @children
        }
    }
}

export component Switch inherits Rectangle {
    property <bool> isOn: false;
    Indicator {
        isOn: root.isOn;
        TouchArea {
            HorizontalLayout {
                alignment: isOn ? start : end;
                padding-left: 20px;
                padding-right: 20px;

                Rectangle {
                    border-radius: 8px;
                    background: black;
                    width: 16px;
                    height: 16px;
                }

            }
            clicked => {
                isOn = !isOn;
            }
        }
    }
}

export component Status inherits Rectangle {
    Indicator {
        VerticalLayout{
            alignment: center;

            HorizontalLayout {
                alignment: center;
                Text {
                    text: "bruh";
                }
            }
        }
    }
}
